# Tomcat
server:
  port: 8081

# Spring
spring:
  application:
    # 应用名称
    name: nacos-dubbo-provider
  profiles:
    # 环境配置
    active: dev

# Dubbo
dubbo:
  application:
    logger: slf4j
    # 关闭qos端口避免单机多生产者端口冲突 如需使用自行开启
    qos-enable: false
    # 元数据中心 local 本地 remote 远程 这里使用远程便于其他服务获取
    metadataType: remote
    # 可选值 interface、instance、all，默认是 all，即接口级地址、应用级地址都注册
    register-mode: instance
    service-discovery:
      # FORCE_INTERFACE，只消费接口级地址，如无地址则报错，单订阅 2.x 地址
      # APPLICATION_FIRST，智能决策接口级/应用级地址，双订阅
      # FORCE_APPLICATION，只消费应用级地址，如无地址则报错，单订阅 3.x 地址
      migration: FORCE_APPLICATION
  protocol:
    # 使用 dubbo 协议通信
    name: dubbo
    # dubbo 协议端口(-1表示自增端口,从20880开始)
    port: -1
  # 注册中心配置
  registry:
    address: nacos://localhost:8848
    group: DUBBO_GROUP
    parameters:
      namespace: ${spring.profiles.active}
  scan:
    # 接口实现类扫描
    base-packages: com.strr.dubbo