spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: password
      database: 0
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          max-wait: -1ms
          min-idle: 0